image: 
 - Visual Studio 2017

environment:
  matrix:
    - CONFIG: Release
    - CONFIG: Debug

install:
  - echo "Building %CONFIG% build"
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - curl -fsS -o oalinst.zip http://www.openal.org/downloads/oalinst.zip
  - 7z x oalinst.zip
  - oalinst.exe /silent

build_script:
  - mkdir build
  - cd build
  - conan install .. -s build_type=%CONFIG% --build missing
  - cmake .. "-GVisual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%CONFIG% -DUNIT_TEST=ON
  - cmake --build . --config "%CONFIG%" -- /maxcpucount:4

test_script:
  - ctest -VV -C "%CONFIG%" --output-on-failure

after_test:
  - if "%CONFIG%"=="Release" ..\tools\windows\build.cmd

artifacts:
  # References here need to have "build\" prepended since 
  # the context here is from the original build folder 
  # before we "cd build" 
  - path: tooter-*.exe
    name: TTInstaller

deploy:
  provider: FTP
  protocol: ftp
  host: anothermessageboard.com
  username: builds@anothermessageboard.com
  password:
    secure: 9Hm8Tj0tt2lXHlXjk3bxyQ==
  folder: /
  on:
    branch: master
    CONFIG: Release

notifications:
  - provider: Email
    to:
      - max@amb.dog
    on_build_success: false
    on_build_failure: true