image: 
 - Visual Studio 2017

environment:
  matrix:
    - CONFIG: Release
    - CONFIG: Debug

install:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add owl https://api.bintray.com/conan/zethon/owl
  - curl -fsS -o oalinst.zip http://www.openal.org/downloads/oalinst.zip
  - 7z x oalinst.zip
  - oalinst.exe /silent

build_script:
  - mkdir build
  - cd build
  - conan install .. -s build_type=%CONFIG% --build missing
  - cmake .. "-GVisual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%CONFIG% -DUNIT_TEST=ON
  - cmake --build . --config "%CONFIG%" -- /maxcpucount:4

test_script:
  - ctest -VV -C "%CONFIG%" --output-on-failure
